In [1]:
import scipy.stats


def test_compatible_mean(sample1, sample2):
    """
    We check if the mean of the two samples is not
    significantly different
    """
    ts, p_value = scipy.stats.ttest_ind(
        sample1, sample2, equal_var=False, alternative="two-sided"
    )
    
#     print(type(p_value))
    
#     print(p_value >= 0.05)
    
#     print(np.size(p_value >= 0.05) - np.count_nonzero(p_value >= 0.05))

    alpha = 0.05
    
    alpha_prime = 1 - (1 - alpha)**(1 / sample1.shape[1])
#     print(alpha_prime)
    
    return np.size(p_value >= alpha_prime) - np.count_nonzero(p_value >= alpha_prime)

    # Pre-determined threshold
#     alpha = 0.05

#     assert p_value >= alpha, "T-test rejected the null hyp. at the 2 sigma level"

#     return ts, p_value

In [25]:
# Script to train machine learning model.

from sklearn.model_selection import train_test_split

# Add the necessary imports for the starter code.
import pandas as pd
from ml.data import process_data
from ml.model import compute_model_metrics
import numpy as np

# Add code to load in the data.
data = pd.read_csv("../data/clean_census.csv")

# Optional enhancement, use K-fold cross validation instead
# of a train-test split.

test = 1

# while test:
#     print(test)

train, test = train_test_split(data, test_size=0.20)

cat_features = [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country",
]
X_train, y_train, encoder, lb = process_data(train,
                                             categorical_features=cat_features,
                                             label="salary", training=True)

# Proces the test data with the process_data function.
X_test, y_test, encoder, lb = process_data(test,
                                             categorical_features=cat_features,
                                             label="salary", training=False,
                                             encoder=encoder, lb=lb)

#     print(y_test)                                             

    # Train and save a model.
#     test = test_compatible_mean(X_train, X_test)

In [66]:
from sklearn import preprocessing
import numpy as np

scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler()

In [67]:
scaler.mean_

array([3.85871852e+01, 1.89717136e+05, 1.00873771e+01, 1.08100994e+03,
       8.71697251e+01, 4.04586916e+01, 5.67030098e-02, 2.95224201e-02,
       6.38052826e-02, 2.68734644e-04, 6.96368243e-01, 3.47435504e-02,
       7.78562654e-02, 4.03101966e-02, 4.22297297e-04, 2.81403563e-02,
       3.56265356e-02, 1.28992629e-02, 5.14434889e-03, 1.01735258e-02,
       1.97711916e-02, 1.52027027e-02, 3.32847052e-02, 4.33046683e-02,
       1.64427211e-01, 1.27840909e-02, 3.24401106e-01, 5.24032555e-02,
       1.61240786e-03, 1.78132678e-02, 2.23011364e-01, 1.35634214e-01,
       6.52641278e-04, 4.62108415e-01, 1.28224816e-02, 3.26973280e-01,
       3.15187346e-02, 3.02902334e-02, 5.69717445e-02, 1.15824631e-01,
       3.45515971e-04, 1.25729423e-01, 1.26228501e-01, 3.10580467e-02,
       4.25752457e-02, 6.03885135e-02, 1.00007678e-01, 4.53009828e-03,
       1.27111486e-01, 2.02318796e-02, 1.10949017e-01, 2.81403563e-02,
       4.99078624e-02, 4.07248157e-01, 2.55259521e-01, 3.00598894e-02,
      

In [68]:
scaler.scale_

array([1.36099806e+01, 1.05693668e+05, 2.56704576e+00, 7.43620101e+03,
       4.02932981e+02, 1.22741256e+01, 2.31274250e-01, 1.69265610e-01,
       2.44405746e-01, 1.63909251e-02, 4.59825525e-01, 1.83129561e-01,
       2.67945269e-01, 1.96685751e-01, 2.05455339e-02, 1.65373748e-01,
       1.85357184e-01, 1.12840028e-01, 7.15393917e-02, 1.00349515e-01,
       1.39213116e-01, 1.22358410e-01, 1.79379022e-01, 2.03542069e-01,
       3.70662789e-01, 1.12341702e-01, 4.68150647e-01, 2.22838853e-01,
       4.01224127e-02, 1.32272277e-01, 4.16265895e-01, 3.42399728e-01,
       2.55385069e-02, 4.98562160e-01, 1.12508069e-01, 4.69107402e-01,
       1.74714922e-01, 1.71384758e-01, 2.31788621e-01, 3.20014509e-01,
       1.85848484e-02, 3.31544167e-01, 3.32106710e-01, 1.73474622e-01,
       2.01897484e-01, 2.38205250e-01, 3.00010237e-01, 6.71533803e-02,
       3.33097818e-01, 1.40792580e-01, 3.14068994e-01, 1.65373748e-01,
       2.17754604e-01, 4.91321784e-01, 4.36006993e-01, 1.70752138e-01,
      

In [69]:
X_scaled = scaler.transform(X_train)
X_scaled

array([[ 0.10380726, -0.61311276, -0.42359087, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       [-1.07180059,  0.44448135, -0.03403802, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       [-0.77789862, -1.54940348, -0.03403802, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       ...,
       [-0.77789862,  0.91389452, -0.42359087, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       [-1.43917804, -1.34862513, -0.03403802, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       [-1.43917804,  0.08468685, -2.37135513, ...,  0.33830208,
        -0.0459995 , -0.02146859]])

In [70]:
X_scaled.mean(axis=0)

array([-1.59577511e-16,  3.05047074e-17, -2.55699093e-16,  2.84639566e-16,
        6.66681510e-16,  2.64661209e-16,  5.10814261e-16,  1.74608869e-15,
        6.55150074e-16, -1.56648940e-15, -1.71481891e-15,  1.82675546e-15,
       -1.15134492e-15,  6.67350679e-16,  1.17144981e-16,  8.70539223e-16,
        9.26570365e-16, -8.73683676e-16,  9.81730949e-16, -4.49134613e-16,
       -3.55758966e-15,  1.07405489e-15,  6.90767314e-16, -1.38741649e-15,
        3.37819283e-16, -3.57910321e-16,  3.94280909e-16,  8.57590599e-16,
        5.34381141e-17,  2.38718409e-16,  8.17647206e-16,  2.68588046e-16,
       -2.28284761e-16,  8.29146675e-16, -2.44000365e-16,  4.99481019e-16,
       -8.69490717e-16,  3.60100037e-16,  1.73050388e-16, -2.78148205e-16,
        2.52352691e-15,  1.17850379e-18, -6.98002433e-16, -4.23202202e-16,
       -2.40996779e-15, -5.47060179e-16, -7.84589429e-17, -2.12777154e-15,
       -1.10438805e-15,  1.11341117e-15,  4.32551381e-16,  9.02056208e-16,
        1.16653974e-15, -

In [71]:
X_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [65]:
X_train[:,105]

array([0., 0., 0., ..., 0., 0., 0.])

In [4]:
X_train.shape[1]

107

In [5]:
test_compatible_mean(X_train, X_test)

0

In [75]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pickle as pkl
import joblib

In [76]:
best_params = {'bootstrap': True, 'max_depth': 110, 'max_features': 3, 'min_samples_leaf': 3, 'min_samples_split': 8, 'n_estimators': 200}

In [73]:
best_params = joblib.load(open("./best_model.joblib", "rb"))
best_params

RandomForestClassifier(max_depth=80, max_features=2, min_samples_leaf=3,
                       min_samples_split=8)

In [77]:
clf = RandomForestClassifier(**best_params)

In [78]:
clf.fit(X_scaled, y_train)

RandomForestClassifier(max_depth=110, max_features=3, min_samples_leaf=3,
                       min_samples_split=8, n_estimators=200)

In [79]:
# scaler = preprocessing.StandardScaler().fit(X_test)
X_test_scaled = scaler.transform(X_test)

In [80]:
X_test_scaled

array([[-0.48399666,  1.00998353,  1.52417339, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       [ 1.57331707,  0.33395438, -0.42359087, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       [-1.14527608,  0.11946661,  1.13462054, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       ...,
       [ 0.03033177, -0.01084394,  0.35551483, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       [ 0.39770922, -0.28200494, -2.37135513, ...,  0.33830208,
        -0.0459995 , -0.02146859],
       [-0.63094764,  0.69329474, -0.03403802, ...,  0.33830208,
        -0.0459995 , -0.02146859]])

In [81]:
y_pred = clf.predict(X_test_scaled)

In [82]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [83]:
# accuracy_score(y_test, y_pred)
compute_model_metrics(y_test, y_pred)

(0.8141783029001074, 0.4877734877734878, 0.6100603621730383)

In [58]:
# accuracy_score(y_test, y_pred)
compute_model_metrics(y_test, y_pred)

(0.8110497237569061, 0.4723294723294723, 0.5969906466043108)

In [24]:
# accuracy_score(y_test, y_pred)
compute_model_metrics(y_test, y_pred)

(0.7890792291220556, 0.4745653573728268, 0.592681946119823)

In [15]:
# accuracy_score(y_test, y_pred)
compute_model_metrics(y_test, y_pred)

(0.8358395989974937, 0.42949130714745654, 0.5674181199489579)

In [ ]:
best_params = pkl.load(open("./best_params_cv4_v2.pkl", "rb"))
best_params

In [ ]:
best_params = pkl.load(open("./best_params_cv4_v3.pkl", "rb"))
best_params

In [ ]:
best_params = pkl.load(open("./best_params_cv4.pkl", "rb"))
best_params

In [ ]:
clf = RandomForestClassifier(**best_params)

In [ ]:
clf.fit(X_train, y_train)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
compute_model_metrics(y_test, y_pred)

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
X_train, y_train, encoder, lb = process_data(data,
                                             categorical_features=cat_features,
                                             label="salary", training=True)

In [ ]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000]
}
# Create a based model
clf = RandomForestClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = clf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

In [ ]:
# Fit the grid search to the data
grid_search.fit(X_train, y_train)

In [ ]:
grid_search.best_params_

In [ ]:
y_test

In [ ]:
X.drop(*[cat_features], axis=1)

In [ ]:
X = train.drop(["salary"], axis=1)
X_categorical = X[cat_features].values
X_continuous = X.drop(*[cat_features], axis=1)
X_continuous

In [ ]:
X = train.drop(["salary"], axis=1)
X_categorical = X[cat_features].values
X_categorical

In [ ]:
X_train

In [ ]:
data

In [ ]:
X_categorical = encoder.fit_transform(X_categorical)